---
- name: Set MySQL Password in debconf selections
  sudo: yes
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
- name: Set MySQL Password Confirmation
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
- name: Installing MySQL
  apt: package={{ item }} state=installed force=yes update_cache=yes
  with_items:
    - mysql-server-{{mysql_server_version}}
