---
- name: install php packages that are relevant to drupal
  apt: name={{ item }} state=latest
  with_items:
      - php7.0
      - php7.0-cli
      - php7.0-common
      - php7.0-mbstring
      - php7.0-gd
      - php7.0-intl
      - php7.0-xml
      - php7.0-mysql
      - php7.0-mcrypt
      - php7.0-zip
      - git
      - php7.0-fpm
      - unzip
      - php-curl
